name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup jdk-${{ matrix.java }}
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: |
          mvn verify -B -V -ntp -Dmaven.javadoc.skip=true
          mvn pmd:pmd -B -ntp